name: 'Update Gist Action'
description: 'This action updates a gist with the commit times of a repository'
author: 'pozuhtuhv'
inputs:
  gist_id:
    description: 'ID of the Gist to update'
    required: true
  user_name:
    description: 'Username for the Gist owner'
    required: true
  access_token:
    description: 'GitHub Personal Access Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: python Commit_Times.py
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        USER_NAME: ${{ inputs.user_name }}
        GIST_ID: ${{ inputs.gist_id }}
branding:
  icon: 'clock'
  color: 'blue'
